export {
  Role,
  type RoleCode,
  Vote,
  type VoteCode,
  type GameState,
  type PlayerState,
  GamePhase,
  type GamePhaseCode,
} from "./src/gameState";
export {
  type RoomState,
  type RoomConfiguration,
  type UserState,
  defaultConfiguration,
} from "./src/roomState";
export {
  type Acknowledgment,
  type Last,
  type AllButLast,
  type FirstArg,
  type ClientToServerEvents,
  type ServerToClientEvents,
  type ErrorAcknowledgment,
  type ErrorState,
} from "./src/events";
export {
  ErrorType,
  type ErrorTypeCode,
  DebatoApiError,
  NotLoggedInError,
  RoomFullError,
  PlayerIsNotMediatorError,
  PlayerNotFoundError,
  RoomAlreadyStartedError,
  RoomLimitReachedError,
  RoomNotFoundError,
  UserNameAlreadyInUseError,
  UserNotFoundInRoomError,
  ValidationError,
  GenericError,
  GameAlreadyStartedError,
  NotEnoughPlayersError,
  PlayerIsNotAntithesisError,
  PlayerIsNotJudgeError,
  PlayerIsNotThesisError,
  NotEnoughRoundsError,
} from "./src/errors";
